<div class="container-fluid">
    <div class="row">
        <div class="customer_table_wrap col-md-12 d-none">
            <table id="customer_table" class="table table-bordered table-hover" cellspacing="0" width="100%">
                <thead class="text-center">
                    <tr>
                        <th>เลขที่</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th>วันคิดดอก</th>
                        <th>วันส่งดอก</th>
                        <th>ราคา</th>
                        <th></th>
                        <th>วันที่ทำรายการ</th>
                        <th>บัตรประชาชน</th>
                    </tr>
                </thead>
                <tfoot class="text-center">
                    <tr>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th></th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                        <th>&nbsp;</th>
                    </tr>
                </tfoot>
                <tbody class="text-center"></tbody>
            </table>
        </div>
    </div>
</div>
<div class="spinner">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>
<?php $this->assets->outputJs();?>