<html>
<head>
    <?php echo $this->tag->getTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='shortcut icon' href="<?php echo $this->url->get('public/img/logo.png')?>" type='image/x-icon' />
    <?php $this->assets->outputCss(); ?>
</head>

<body class="bg">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center" style="margin-top:15%">
                <div style="font-size:128px;">
                    <i class="far fa-frown"></i>
                </div>
                <div style="font-size:64px;">
                    <span>ERROR </span><span style="font-size:112px; color:#dc3545">404</span> 
                </div>
                <div style="font-size:32px;">
                    ไม่พบหน้าที่ต้องการ
                </div>
            </div>
        </div>
    </div>

</body>
<html>