<div class="form-login">
  <form action="signup" method="post" class="login-form">
    <h3 class="text-center">เพิ่มพนักงาน</h3>
    <input type="text" name="username" placeholder="ชื่อผู้ใช้" />
    <input type="password" name="password" placeholder="รหัสผ่าน" />
    <input type="text" name="firstname" placeholder="ชื่อ" autofocus/>
    <input type="text" name="lastname" placeholder="สกุล" />
    <button>เพิ่มพนักงาน</button>
  </form>
</div>