<div class="wrap">
<div class="container-fluid">
    <div class="row">
        <div class="sale_table_wrap col-md-12 d-none">
            <table id="sale_table" class="table table-bordered table-hover" cellspacing="0" width="100%">
                <thead class="text-center">
                    <tr>
                        <th>เลขที่สัญญา</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th>ราคา</th>
                        <th>ราคาตั้งขาย</th>
                        <th>วันที่ตั้งขาย</th>
                        <th>หมายเหตุ</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot class="text-center">
                  <tr>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th></th>
                    <th></th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                  </tr>
                </tfoot>
                <tbody class="text-center"></tbody>
            </table>
        </div>
    </div>
</div>
</div>

<!-- editSaleModal -->
<div class="modal fade" id="editSaleModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">แก้ไข
                    <!--  -->
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                    <form class="editSaleForm" action="#">
                      <input type="hidden" name="account_id" class="account_id">
                        <div class="form-group row">
                          <label class="col-sm-6 col-form-label custom-label">ราคาตั้งขาย</label>
                          <div class="col-sm-6">
                            <input type="text" name="sale_value" class="sale_value custom-input" required autofocus>
                          </div>
                        </div>
                        <div class="form-group row">
                          <label class="col-sm-6 col-form-label custom-label">หมายเหตุ</label>
                          <div class="col-sm-6">
                            <input type="text" name="note" class="custom-input note">
                          </div>
                        </div>
                        <br>
                        <br>
                        <div class="form-group row">
                        <div class="col-sm-6">
                          <button type="submit" class="confirm-edit-separate-sale-transaction btn btn x-rounded btn-custom btn-outline-primary w-100">
                            ยืนยันการแก้ไข
                        </button>
                        </div>
                        <div class="col-sm-6">
                          <button type="button" class="confirm-delete-sale-transaction btn x-rounded btn-custom btn-outline-primary w-100">
                            ยกเลิกตั้งขาย
                          </button>
                        </div>
                        </div>
                  </form>
            </div>
        </div>
    </div>
</div>
<div class="spinner">
  <div class="rect1"></div>
  <div class="rect2"></div>
  <div class="rect3"></div>
  <div class="rect4"></div>
  <div class="rect5"></div>
</div>
<!-- separateSaleModal -->
<div class="modal fade" id="separateSaleModal">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form class="separateSaleForm" action="#">
            <input type="hidden" name="product_id" class="product_id" value="">
            <div class="form-group row">
              <label class="col-sm-6 col-form-label custom-label">วันที่ทำรายการ</label>
              <div class="col-sm-6">
                <input type="text" name="transaction_date" class="custom-input transaction_date">
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-6 col-form-label custom-label">เวลาที่ทำรายการ</label>
              <div class="col-sm-6">
                <input type="text" name="transaction_time" class="custom-input transaction_time">
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-6 col-form-label custom-label">สินค้า</label>
              <div class="col-sm-6">
                <input type="text" name="product_name" class="custom-input product_name" required autofocus>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-6 col-form-label custom-label">ยี่ห้อ</label>
              <div class="col-sm-6">
                <input type="text" name="product_brand" class="custom-input product_brand">
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-6 col-form-label custom-label">รายละเอียด</label>
              <div class="col-sm-6">
                <input type="text" name="product_detail" class="custom-input product_detail">
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-6 col-form-label custom-label">ราคารับมา</label>
              <div class="col-sm-6">
                <input type="text" name="product_value" class="custom-input product_value" required>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-6 col-form-label custom-label">ราคาตั้งขาย</label>
              <div class="col-sm-6">
                <input type="text" name="sale_value" class="custom-input sale_value" required>
              </div>
            </div>
            <div class="form-group row">
              <label class="col-sm-6 col-form-label custom-label">หมายเหตุ</label>
              <div class="col-sm-6">
                <input type="text" name="note" class="custom-input note">
              </div>
            </div>
            <br>
            <br>
            <button type="submit" class="confirm-separate-sale btn btn-custom btn-outline-primary x-rounded w-100">
                ยืนยันแยกขายสินค้า
            </button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- editseparateSaleModal -->
<div class="modal fade" id="editseparateSaleModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">แก้ไข
                    <!--  -->
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                    <form class="editseparateSaleForm" action="#">
                      <input type="hidden" name="account_id" class="account_id">
                        <div class="form-group row">
                          <label class="col-sm-6 col-form-label custom-label">ราคาตั้งขาย</label>
                          <div class="col-sm-6">
                            <input type="text" name="sale_value" class="sale_value custom-input" required autofocus>
                          </div>
                        </div>
                        <div class="form-group row">
                          <label class="col-sm-6 col-form-label custom-label">หมายเหตุ</label>
                            <div class="col-sm-6">
                              <input type="text" name="note" class="custom-input note">
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class="form-group row">
                        <div class="col-sm-6">
                          <button type="submit" class="confirm-edit-separate-sale-transaction btn btn x-rounded btn-custom btn-outline-primary w-100">
                            ยืนยันการแก้ไข
                        </button>
                        </div>
                        <div class="col-sm-6">
                          <button type="button" class="confirm-delete-separate-sale-transaction btn x-rounded btn-custom btn-outline-primary w-100">
                            ยกเลิกแยกขาย
                          </button>
                        </div>
                        </div>
                  </form>
            </div>
        </div>
    </div>
</div>
<?php $this->assets->outputJs(); ?>


